version: '3.8'

services:
  app:
    image: zahit/minio-api:latest
    container_name: minio-api
    environment:
      URL: "minio"
    ports:
      - 8000:8000
  minio:
    image: bitnami/minio:2021.10.23
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "password"
      URL: "minio"
    volumes:
      - ./data/minio-persistence:/data
      - ./data/minio-persistence/certs:/certs
    ports:
      - 9000:9000
      - 9001:9001

  postgresql:
    image: postgres:11.4
    container_name: postgresql-minio
    restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: minio
    command: "
                postgres
                  -c max_connections=200
                  -c logging_collector=on
                  -c log_min_messages=LOG
                  -c log_directory=/var/log/postgresql"
    ports:
      - 5432:5432